const express = require('express');
const router  = express.Router();
const Car = require('../models/car');

//contains routes for add, edit & delete
//show is done along with car-details

/*  */
const loginCheck = () => {
  return (req, res, next) => 
    (req.session.user ? next () : res.redirect('/'));
};

/* prefixed with /myaccount/insurance in app.js*/
//Add Insurance
router.post('/add/:carId', loginCheck(), (req, res, next) => {
  const carId = req.params.carId; //needed to add te insurance to the correct car
  const loggedUser = req.session.user;

  const name = req.body.name;
  const typ = req.body.typ;
  const abschluss_jahr = req.body.abschluss_jahr;
  const abschluss_kilometerstand = req.body.abschluss_kilometerstand;
  const geschaetzte_laufleistung = req.body.geschaetzte_laufleistung;
  const betrag = req.body.betrag;
  const schadensfreiheitsklasse = req.body.schadensfreiheitsklasse;
  
  //_id should be created & generated by mongoDB automatically
  const newInsurance = {
    name: name,
    typ: typ,
    abschluss_jahr: abschluss_jahr,
    abschluss_kilometerstand: abschluss_kilometerstand,
    geschaetzte_laufleistung: geschaetzte_laufleistung,
    betrag: betrag,
    schadensfreiheitsklasse: schadensfreiheitsklasse
  }

  Car.findOne({ "kennzeichen": carId })
    .then(foundCar => {
      if (foundCar !== null) {
        foundCar.versicherungsbuch.push(newInsurance);
      }
    })
    .catch(err => {
      next(err);
    });
});

module.exports = router;
